name: apluscredit
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/aplus.png
    - assets/score.png
    - assets/test1.webp
    - assets/test2.webp
    - assets/test3.webp
    - assets/test4.webp
    - assets/credit.webp
  uses-material-design: true
